"""Build the curated 50-tool Agent-facing AKShare docs index."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

OUTPUT_PATH = Path("docs/akshare/tools/stock_tools.json")

STOCK_PARAM = {
    "stock": {
        "type": "string",
        "required": True,
        "description": "A 股名称或六位股票代码",
        "examples": ["贵州茅台", "600519"],
    }
}
SYMBOL_PARAM = {
    "symbol": {
        "type": "string",
        "required": True,
        "description": "接口所需的代码或品种标识",
        "examples": ["000001", "sh000001"],
    }
}
DATE_PARAM = {
    "date": {
        "type": "string",
        "required": False,
        "description": "日期，通常为 YYYYMMDD",
        "examples": ["20260610"],
    }
}


def item(
    name: str,
    category: str,
    description: str,
    source: str,
    aliases: list[str],
    example: str,
    *,
    params: dict[str, Any] | None = None,
    mode: str = "generic",
) -> dict[str, Any]:
    """Create one concise tool contract."""

    return {
        "tool_name": name,
        "category": category,
        "description": description,
        "params": params or {},
        "returns": {"type": "object", "description": "标准化的 AKShare 查询结果"},
        "example_query": [example],
        "source_interfaces": [source],
        "aliases": aliases,
        "enabled": True,
        "mode": mode,
    }


TOOLS = [
    item(
        "resolve_stock",
        "identity",
        "解析 A 股名称或代码",
        "stock_info_a_code_name",
        ["股票代码", "股票名称", "解析股票"],
        "贵州茅台的代码是什么",
        params=STOCK_PARAM,
        mode="resolve_stock",
    ),
    item(
        "list_a_share_stocks",
        "identity",
        "查询全部 A 股代码和名称",
        "stock_info_a_code_name",
        ["股票列表", "全部股票"],
        "有哪些 A 股",
    ),
    item(
        "get_stock_company_profile",
        "company",
        "查询上市公司基本资料",
        "stock_individual_info_em",
        ["公司资料", "公司信息", "主营业务"],
        "介绍一下宁德时代",
        params=STOCK_PARAM,
        mode="company",
    ),
    item(
        "get_stock_listing_info",
        "company",
        "查询股票上市和发行信息",
        "stock_individual_info_em",
        ["上市时间", "发行信息"],
        "贵州茅台什么时候上市",
        params=STOCK_PARAM,
        mode="company",
    ),
    item(
        "get_stock_realtime_quote",
        "stock_realtime",
        "查询单只 A 股最新价格、涨跌幅和成交信息",
        "stock_zh_a_spot_em",
        ["实时行情", "最新价", "现在多少钱", "涨跌幅", "股价"],
        "贵州茅台现在多少钱",
        params=STOCK_PARAM,
        mode="realtime_quote",
    ),
    item(
        "get_a_share_market_snapshot",
        "stock_realtime",
        "查询全部 A 股实时行情快照",
        "stock_zh_a_spot_em",
        ["全市场行情", "市场快照"],
        "今天 A 股整体行情",
    ),
    item(
        "get_stock_bid_ask",
        "stock_realtime",
        "查询股票买卖盘口报价",
        "stock_bid_ask_em",
        ["盘口", "买一", "卖一"],
        "贵州茅台买一卖一是多少",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_intraday_ticks",
        "stock_realtime",
        "查询股票日内逐笔成交",
        "stock_intraday_em",
        ["逐笔成交", "分笔"],
        "查看贵州茅台今天逐笔成交",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_intraday_minutes",
        "stock_realtime",
        "查询股票日内分钟行情",
        "stock_zh_a_hist_min_em",
        ["分钟行情", "分时"],
        "贵州茅台今天分时走势",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_order_book",
        "stock_realtime",
        "查询股票五档盘口",
        "stock_bid_ask_em",
        ["五档盘口", "委托盘"],
        "查看 600519 五档盘口",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_realtime_trades",
        "stock_realtime",
        "查询股票实时成交记录",
        "stock_intraday_em",
        ["实时成交", "成交明细"],
        "贵州茅台最新成交明细",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_market_status",
        "market",
        "查询证券市场最近交易状态",
        "stock_sse_summary",
        ["开盘状态", "交易状态"],
        "今天股市开盘了吗",
    ),
    item(
        "get_stock_daily_history",
        "stock_history",
        "查询股票日线历史行情",
        "stock_zh_a_hist",
        ["历史行情", "日线", "走势"],
        "贵州茅台过去一个月走势",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "最近自然日数量",
                "default": 30,
            },
            "adjust": {
                "type": "string",
                "required": False,
                "description": "复权方式",
                "default": "",
            },
        },
        mode="history",
    ),
    item(
        "get_stock_weekly_history",
        "stock_history",
        "查询股票周线历史行情",
        "stock_zh_a_hist",
        ["周线", "周走势"],
        "贵州茅台最近周线",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "最近自然日数量",
                "default": 365,
            },
            "period": {
                "type": "string",
                "required": False,
                "description": "周期",
                "default": "weekly",
            },
        },
        mode="history",
    ),
    item(
        "get_stock_monthly_history",
        "stock_history",
        "查询股票月线历史行情",
        "stock_zh_a_hist",
        ["月线", "月走势"],
        "贵州茅台最近月线",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "最近自然日数量",
                "default": 730,
            },
            "period": {
                "type": "string",
                "required": False,
                "description": "周期",
                "default": "monthly",
            },
        },
        mode="history",
    ),
    item(
        "get_stock_adjusted_history",
        "stock_history",
        "查询股票复权历史行情",
        "stock_zh_a_hist",
        ["前复权", "后复权", "复权"],
        "贵州茅台前复权走势",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "最近自然日数量",
                "default": 365,
            },
            "adjust": {
                "type": "string",
                "required": False,
                "description": "qfq 或 hfq",
                "default": "qfq",
            },
        },
        mode="history",
    ),
    item(
        "get_stock_period_performance",
        "stock_history",
        "查询股票区间价格表现",
        "stock_zh_a_hist",
        ["区间表现", "累计涨幅"],
        "贵州茅台今年涨了多少",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "区间自然日数",
                "default": 365,
            },
        },
        mode="history",
    ),
    item(
        "get_stock_volatility",
        "stock_history",
        "查询股票历史波动情况",
        "stock_zh_a_hist",
        ["波动率", "振幅"],
        "贵州茅台最近波动大吗",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "区间自然日数",
                "default": 90,
            },
        },
        mode="history",
    ),
    item(
        "get_stock_price_summary",
        "stock_history",
        "查询股票历史价格摘要",
        "stock_zh_a_hist",
        ["价格摘要", "最高最低"],
        "贵州茅台一年最高最低价",
        params={
            **STOCK_PARAM,
            "days": {
                "type": "integer",
                "required": False,
                "description": "区间自然日数",
                "default": 365,
            },
        },
        mode="history",
    ),
    item(
        "get_stock_financial_indicators",
        "financial",
        "查询股票综合财务分析指标",
        "stock_financial_analysis_indicator",
        ["财务指标", "财报", "盈利能力"],
        "贵州茅台最近财务指标",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_balance_sheet",
        "financial",
        "查询股票资产负债表",
        "stock_balance_sheet_by_report_em",
        ["资产负债表", "资产", "负债"],
        "贵州茅台资产负债表",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_income_statement",
        "financial",
        "查询股票利润表",
        "stock_profit_sheet_by_report_em",
        ["利润表", "营收", "净利润"],
        "贵州茅台利润表",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_cash_flow_statement",
        "financial",
        "查询股票现金流量表",
        "stock_cash_flow_sheet_by_report_em",
        ["现金流量表", "现金流"],
        "贵州茅台现金流怎么样",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_profitability",
        "financial",
        "查询股票盈利能力指标",
        "stock_financial_analysis_indicator",
        ["盈利能力", "ROE", "毛利率"],
        "贵州茅台盈利能力如何",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_growth_metrics",
        "financial",
        "查询股票成长能力指标",
        "stock_financial_analysis_indicator",
        ["成长能力", "增长率"],
        "宁德时代成长性如何",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_solvency_metrics",
        "financial",
        "查询股票偿债能力指标",
        "stock_financial_analysis_indicator",
        ["偿债能力", "资产负债率"],
        "贵州茅台偿债能力",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_operating_metrics",
        "financial",
        "查询股票营运能力指标",
        "stock_financial_analysis_indicator",
        ["营运能力", "周转率"],
        "贵州茅台营运能力",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_dupont_analysis",
        "financial",
        "查询股票杜邦分析指标",
        "stock_financial_analysis_indicator",
        ["杜邦分析", "ROE 分解"],
        "贵州茅台杜邦分析",
        params=STOCK_PARAM,
        mode="financial",
    ),
    item(
        "get_stock_financial_forecast",
        "financial",
        "查询机构盈利预测",
        "stock_profit_forecast_em",
        ["盈利预测", "业绩预测"],
        "机构如何预测贵州茅台业绩",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_shareholders",
        "ownership",
        "查询股票股东户数",
        "stock_zh_a_gdhs",
        ["股东户数", "股东人数"],
        "贵州茅台股东户数",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_top_shareholders",
        "ownership",
        "查询股票前十大股东",
        "stock_gdfx_top_10_em",
        ["十大股东", "主要股东"],
        "贵州茅台前十大股东",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_shareholder_changes",
        "ownership",
        "查询股票股东变化",
        "stock_zh_a_gdhs_detail_em",
        ["股东变化", "股东增减"],
        "贵州茅台股东人数变化",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_dividend_history",
        "ownership",
        "查询股票历史分红",
        "stock_history_dividend_detail",
        ["分红", "派息", "送股"],
        "贵州茅台分红历史",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_share_capital",
        "ownership",
        "查询股票股本结构",
        "stock_individual_info_em",
        ["股本结构", "总股本", "流通股"],
        "贵州茅台总股本",
        params=STOCK_PARAM,
        mode="company",
    ),
    item(
        "get_stock_restricted_share_unlocks",
        "ownership",
        "查询限售股解禁安排",
        "stock_restricted_release_queue_em",
        ["解禁", "限售股"],
        "贵州茅台近期有解禁吗",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_buybacks",
        "ownership",
        "查询股票回购记录",
        "stock_repurchase_em",
        ["回购", "股份回购"],
        "贵州茅台最近有回购吗",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_news",
        "events",
        "查询股票最近新闻",
        "stock_news_em",
        ["新闻", "消息", "资讯"],
        "贵州茅台最近有什么新闻",
        params={
            **STOCK_PARAM,
            "limit": {
                "type": "integer",
                "required": False,
                "description": "最多返回条数",
                "default": 5,
            },
        },
        mode="news",
    ),
    item(
        "get_stock_announcements",
        "events",
        "查询上市公司公告",
        "stock_notice_report",
        ["公告", "公司公告"],
        "贵州茅台最近公告",
        params=DATE_PARAM,
    ),
    item(
        "get_stock_major_events",
        "events",
        "查询上市公司重大事项公告",
        "stock_notice_report",
        ["重大事项", "重大事件"],
        "贵州茅台最近重大事项",
        params=DATE_PARAM,
    ),
    item(
        "get_stock_management_changes",
        "events",
        "查询上市公司高管变动信息",
        "stock_ggcg_em",
        ["高管变动", "管理层变化"],
        "贵州茅台高管最近有变化吗",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_suspension_events",
        "events",
        "查询股票停复牌信息",
        "stock_tfp_em",
        ["停牌", "复牌"],
        "今天有哪些股票停牌",
        params=DATE_PARAM,
    ),
    item(
        "get_stock_valuation",
        "trading_behavior",
        "查询股票估值指标",
        "stock_zh_valuation_baidu",
        ["估值", "市盈率", "市净率"],
        "贵州茅台估值高吗",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_fund_flow",
        "trading_behavior",
        "查询个股资金流向",
        "stock_individual_fund_flow",
        ["资金流向", "主力资金"],
        "贵州茅台今天资金流向",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_northbound_holding",
        "trading_behavior",
        "查询北向资金持股",
        "stock_hsgt_hold_stock_em",
        ["北向资金", "陆股通持股"],
        "北向资金持有贵州茅台多少",
        params=STOCK_PARAM,
    ),
    item(
        "get_stock_margin_trading",
        "trading_behavior",
        "查询融资融券明细",
        "stock_margin_detail_sse",
        ["融资融券", "融资余额"],
        "贵州茅台融资融券情况",
        params=DATE_PARAM,
    ),
    item(
        "get_stock_dragon_tiger_list",
        "trading_behavior",
        "查询龙虎榜明细",
        "stock_lhb_detail_em",
        ["龙虎榜"],
        "今天龙虎榜有哪些股票",
        params=DATE_PARAM,
    ),
    item(
        "get_market_overview",
        "market_context",
        "查询 A 股市场总体概况",
        "stock_sse_summary",
        ["市场概况", "市场总貌"],
        "今天 A 股市场概况",
    ),
    item(
        "get_industry_rankings",
        "market_context",
        "查询行业板块排行",
        "stock_board_industry_name_em",
        ["行业排行", "行业板块"],
        "今天哪些行业涨得好",
    ),
    item(
        "get_concept_rankings",
        "market_context",
        "查询概念板块排行",
        "stock_board_concept_name_em",
        ["概念排行", "概念板块"],
        "今天哪些概念板块强",
    ),
    item(
        "get_index_realtime_quote",
        "market_context",
        "查询指数实时行情",
        "stock_zh_index_spot_em",
        ["指数行情", "上证指数", "指数点位"],
        "上证指数现在多少点",
        params=SYMBOL_PARAM,
    ),
]


def main() -> None:
    """Write the curated docs index."""

    if len(TOOLS) != 50:
        raise ValueError(f"Expected 50 tools, found {len(TOOLS)}")
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        json.dumps({"schema_version": 1, "tools": TOOLS}, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(TOOLS)} tools to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
